---
title: "problemOne"
author: "Daniel Emaasit"
date: "February 10, 2015"
output: word_document
---

## Problem C17.1
Use the data in PNTSPRD.RAW for this exercise:

# Section (i)
The variable favwin is a binary variable if the team favored by the Las Vegas
point spread wins. A linear probability model to estimate the probability that the favored team wins is:
P(favwin=1|spread)=beta0 + beta1(spread)

Explain why, if the spread incorporates all relevant information, we expect beta0=0.5

# subsection (ii)

Estimate the model from part (i) by OLS. Test H0:0.5 against a two-sided
alternative. Use both the usual and heteroskedasticity-robust standard errors.

```{r}
## install packages to read dta files
install.packages("devtools")
library("devtools")
devtools::install_github("hadley/haven")
library(haven)

## reada the data file into R
data1<-read_dta("PNTSPRD.dta")
head(data1)
```

# Subsection (iii)
Is spread statistically significant? What is the estimated probability that the
favored team wins when spread=10?

# Subsection (iv)
Now, estimate a probit model for P( favwin  1spread ). Interpret and test the null hypothesis that the intercept is zero. [Hint: Remember that theta= 0.5.]


# Subsection (v)
Use the probit model to estimate the probability that the favored team wins when
spread  10. Compare this with the LPM estimate from part (iii).


# Subsection (vi)
Add the variables favhome, fav25, and und25 to the probit model and test joint significance of these variables using the likelihood ratio test. (How many df are in the chi-square distribution?) Interpret this result, focusing on the question of whether the spread incorporates all observable information prior to a game.


## Problem C17.2

Use the data in LOANAPP.RAW for this exercise

# Subsection (i)
Estimate a probit model of approve on white. Find the estimated probability of
loan approval for both whites and nonwhites. How do these compare with the
linear probability estimates?

# Subsection (ii)
Now, add the variables hrat, obrat, loanprc, unem, male, married, dep, sch,
cosign, chist, pubrec, mortlat1, mortlat2, and vr to the probit model. Is there
statistically significant evidence of discrimination against nonwhites?

# Subsction (iii)
Estimate the model from part (ii) by logit. Compare the coefficient on white to the
probit estimate.


# Subsection (iv)
Use equation (17.17) to estimate the sizes of the discrimination effects for probit and logit.


## Problem C17.3
Use the data in FRINGE.RAW for this exercise

# Subsection (i)
For what percentage of the workers in the sample is pension equal to zero? What
is the range of pension for workers with nonzero pension benefits? Why is a Tobit
model appropriate for modeling pension?


# Subsection (ii)
Estimate a Tobit model explaining pension in terms of exper, age, tenure, educ,
depends, married, white, and male. Do whites and males have statistically significant higher expected pension benefits?


# Subsection (iii)
Use the results from part (ii) to estimate the difference in expected pension
benefits for a white male and a nonwhite female, both of whom are 35 years old,
are single with no dependents, have 16 years of education, and have 10 years of
experience.


# Subsection (iv)
Add union to the Tobit model and comment on its significance.


# Subsection (v)
Apply the Tobit model from part (iv) but with peratio, the pension-earnings ratio,
as the dependent variable. (Notice that this is a fraction between zero and one, but,though it often takes on the value zero, it never gets close to being unity. Thus, a Tobit model is fine as an approximation.) Does gender or race have an effect on the pension-earnings ratio?











